### PR TITLE
Fix for 'UnboundLocalError: local variable 'user_names' referenced be…

### PR DESCRIPTION
**Pull request by nuschpl**
…fore assignment in line 926

### CODE REVIEW

**Comment by darryllane** [comment]
Hi! Id like to recreate this issue, would you mind sharing how you got to it?

**Comment by nuschpl** [comment]
I can't share the domain scanned but it's obvious looking at the code
where  the flow wrongly assumes variable is always set while it's not in
some cases

niedz., 18 lis 2018, 11:48 użytkownik Darryl <notifications@github.com>
napisał:

**Comment by nuschpl** [comment]
If you do "if variable:"  in python it will check if variable has value,
will check if variable is "", will check even if variable is None, but if
variable is not set at all at the time it will raise NameError. So you need
to either catch NameError exception or preinitialize all variables which
have possibility to not being set with None in their full scope
Regards
B.Ż

niedz., 18 lis 2018, 12:18 użytkownik Bartłomiej Żogała <nusch@nusch.pl>
napisał:

**Comment by darryllane** [comment]
Thats fair enough, ill take a look when i get home

**Pull request merged**
